// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGpq2-bIQCnufM-Tb2Kj7VJdd-jH5KjtE',
    appId: '1:617536874371:android:252de2706cffae3c8638b6',
    messagingSenderId: '617536874371',
    projectId: 'carrot-market-cc',
    storageBucket: 'carrot-market-cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQDZZnPMZyuY5GADADORYQ0Xo7UsnwIBA',
    appId: '1:617536874371:ios:d150266f69209b298638b6',
    messagingSenderId: '617536874371',
    projectId: 'carrot-market-cc',
    storageBucket: 'carrot-market-cc.appspot.com',
    iosClientId:
        '617536874371-q4gm9ir9ril7oibgs42j1ik3fvc233ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.carrotMarketCc',
  );
}
